In [5]:
import selenium
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import re

In [7]:
URL = 'https://api.visitkorea.or.kr/search/commonList.do'

관광지명 = []
지역 = []
cnt = 0
# 홈페이지 열기
driver = webdriver.Chrome(executable_path='../chromedriver')
driver.get(url=URL)
driver.implicitly_wait(time_to_wait=3)

# 쇼핑, 음식점 카테고리 제거하기
driver.find_element_by_xpath('//*[@id="typeid_38"]').click()
time.sleep(1)
driver.find_element_by_xpath('//*[@id="typeid_39"]').click()
driver.implicitly_wait(time_to_wait=3)
time.sleep(2)

# 홀홀
driver.find_element_by_xpath('//*[@id="selectDiv"]/table/tbody/tr[2]/td/div[1]/span[1]/select[1]/option[2]').click()
driver.implicitly_wait(time_to_wait=3)
time.sleep(2)

driver.find_element_by_xpath('//*[@id="selectDiv"]/table/tbody/tr[2]/td/div[2]/a[1]').click()
driver.implicitly_wait(time_to_wait=3)
time.sleep(2)

driver.find_element_by_xpath('//*[@id="selectDiv"]/table/tbody/tr[2]/td/div[1]/span[2]/select[1]/option[4]').click()
driver.implicitly_wait(time_to_wait=3)
time.sleep(2)



# 메뉴 50개씩 보기
driver.find_element_by_xpath('//*[@id="numOfPage"]/option[5]').click()
driver.implicitly_wait(time_to_wait=1)
driver.find_element_by_xpath('//*[@id="numOfPageView"]').click()
driver.implicitly_wait(time_to_wait=5)

while True:
    # 페이지 넘어가기 알고리즘
    try:
        if cnt == 10:
            driver.find_element_by_xpath('//*[@id="content"]/div[6]/a[3]').click()
            driver.implicitly_wait(time_to_wait=3)
            time.sleep(2)
            cnt = 0

        if cnt >= 1:
            driver.find_element_by_xpath('//*[@id="content"]/div[6]/span/a[{}]'.format(cnt)).click()
            driver.implicitly_wait(time_to_wait=3)
            time.sleep(2)
            cnt += 1

        if cnt == 0:
            cnt += 1
    except:
        break
        
        
    # 해당 페이지 소스 받아오기
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    attraction = soup.select('#listForm > ul > li > a > dl > dt')
    location = soup.select('#listForm > ul > li > a > dl > dd > strong')

    for i in range(len(attraction)):
        관광지명.append(attraction[i].text)
        지역.append(location[i].text)

KeyboardInterrupt:

In [ ]:
print("관광지명 list 길이 : {}, 지역 list 길이 :  {}".format(len(관광지명), len(지역)))

In [13]:
# 이상한 놈 있다 찾아보기
cnt_1 = 0
cnt_1_1= []

cnt_2 = 0
cnt_2_2= []

cnt_3 = 0
del_1 = []
del_2 = []

for i in range(len(지역)):
    if '관광지' in  지역[i]:
        cnt_1 += 1
        cnt_1_1.append(i)
        
    elif '레포츠' in 지역[i]:
        cnt_2 += 1
        cnt_2_2.append(i)
    else:
        cnt_3 += 1
        del_1.append(관광지명[i])
        del_2.append(지역[i])

In [14]:
# 이상한 놈 지우기
for i in del_1:
    관광지명.remove(i)
for j in del_2:
    지역.remove(j)

In [15]:
지역[666] = '[관광지] 울산시 울주군청'
지역[1131] = '[관광지] 강원도 양양군'

In [16]:
분류 = []
for i in 지역:
    분류.append(i[1:4])

In [17]:
hangul = re.compile('[^ ㄱ-ㅣ가-힣]+')

for i in range(len(지역)):
    result = hangul.sub('', 지역[i]) 
    지역[i] = result
    지역[i] = 지역[i][3:]

In [18]:
for i in range(len(지역)):
    if "  " == 지역[i]:
        print(i)

In [19]:
import pandas as pd
문화시설 = pd.DataFrame(data=관광지명)
문화시설["area"] = 지역
문화시설['Class'] = 분류
문화시설.columns = [['name','area','class']]

In [20]:
문화시설

                      name       area class
0                    수타사계곡   강원도 홍천군    관광지
1               승봉도 이일레 해변    인천 옹진군    관광지
2     덕구계곡 (경북 동해안 국가지질공원)  경상북도 울진군    관광지
3                      외달도  전라남도 목포시    관광지
4                       독도  경상북도 울릉군    관광지
...                    ...        ...   ...
4296                   도솔산   강원도 양구군    관광지
4297               진동 계곡마을   강원도 인제군    관광지
4298                 연가리샘터   강원도 인제군    관광지
4299                 연가리계곡   강원도 인제군    관광지
4300              강촌환경생태연못   강원도 춘천시    관광지

[4301 rows x 3 columns]

In [21]:
문화시설.to_csv('./문화시설(관광지,레포츠).csv',index=False,encoding='UTF-8')

In [22]:
asd = pd.read_csv('./문화시설(관광지,레포츠).csv')

In [23]:
asd

                      name       area class
0                    수타사계곡   강원도 홍천군    관광지
1               승봉도 이일레 해변    인천 옹진군    관광지
2     덕구계곡 (경북 동해안 국가지질공원)  경상북도 울진군    관광지
3                      외달도  전라남도 목포시    관광지
4                       독도  경상북도 울릉군    관광지
...                    ...        ...   ...
4296                   도솔산   강원도 양구군    관광지
4297               진동 계곡마을   강원도 인제군    관광지
4298                 연가리샘터   강원도 인제군    관광지
4299                 연가리계곡   강원도 인제군    관광지
4300              강촌환경생태연못   강원도 춘천시    관광지

[4301 rows x 3 columns]